Adding Support For Localization
AvdLee/Roadmap pull request #19
Opened 2023-02-21 16:01 UTC by cs4alhaider

This changes will add support for localization where we just need to add extra optional parameters in our json:
`localizedTitle`, `localizedDescription` and `localizedStatus`
If one of the above is `nil` then we will look into the original values to use them `title`, `description` and `status`

If you are going to send always the localized values `localizedTitle`, `localizedDescription` and `localizedStatus`, then no need to return the original values `title`, `description` and `status`

```
[
  {
    "id": "0",
    "title": "Adding a map",
    "localizedTitle": [
      {
        "language": "ar",
        "value": "اضافة خارطة"
      },
      {
        "language": "en",
        "value": "Adding a map"
      }
    ],
    "status": "planned",
    "localizedStatus": [
      {
        "language": "ar",
        "value": "مجدولة"
      },
      {
        "language": "en",
        "value": "Planned"
      }
    ],
    "description": "some description",
    "localizedDescription": [
      {
        "language": "ar",
        "value": "اضافة خارطة لمعرفة الاماكن القريبة"
      },
      {
        "language": "en",
        "value": "Adding a map to view nearby places"
      }
    ]
  }
]
```

2023-02-21 17:20 UTC, hiddevdploeg commented on Sources/Roadmap/Models/RoadmapFeature.swift
> +    let originalTitle: String
Would this not break existing `JSON` files? so maybe change `originalTitle`, `originalStatus` and `originalDescriptions` around and rename them to `featureTitle` etc. 

Example:
```
let title : String

var featureTitle : String {
    localizedTitle.currentLocal ?? title
}

```

And then use `featureTitle` in the `View` this way, everyone that already has Roadmap in their app doesn’t have to rewrite their JSON 😄

2023-02-21 17:21 UTC, hiddevdploeg commented on Sources/Roadmap/Models/RoadmapFeature.swift
> +        self?.first(where: { $0.language == L.code })?.value
If this is the only place that uses `L` as a `typealias` for `Language` then maybe it’s not worth it as `Language.code` reads clearer than `L.code`

2023-02-21 17:23 UTC, hiddevdploeg commented on Sources/Roadmap/Models/RoadmapFeature.swift
> +    let originalTitle: String
Aah just see the `CodingKeys`, that would fix it, but my proposal might make the `CodingKeys` unnecessary? 😊

2023-02-21 17:30 UTC, cs4alhaider commented on Sources/Roadmap/Models/RoadmapFeature.swift
> +    let originalTitle: String
Agree with you, will modify it!

2023-02-21 17:30 UTC, cs4alhaider commented on Sources/Roadmap/Models/RoadmapFeature.swift
> +        self?.first(where: { $0.language == L.code })?.value
Agree with you, will modify it!

2023-02-21 17:32 UTC, AvdLee requested changes
Thanks for your contribution, this is a great addition! Would you mind writing a little paragraph in the readme as well so others could localize their features?

2023-02-21 17:32 UTC, AvdLee commented on Sources/Roadmap/Models/RoadmapFeature.swift
> +        self?.first(where: { $0.language == L.code })?.value
Agreed, I don't think the `typealias L` makes things more readable!

2023-02-22 08:41 UTC, merged

2023-02-22 10:17 UTC, hiddevdploeg commented
Thanks for you contribution @cs4alhaider! This closes #17

2023-02-23 16:35 UTC, jordibruin commented
@cs4alhaider this breaks on Monterey

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/170948/220970997-141727f9-1ad9-45ac-bb0f-92fdec6a1121.png">

Can you fix it?