Pull to refresh
AvdLee/Roadmap pull request #29
Opened 2023-02-21 20:44 UTC by JamesSedlacek

I'm unsure if this actually will update the vote count. 
Also should consider trying to maintain the order if it's shuffled.

2023-02-21 20:58 UTC, cs4alhaider commented
@JamesSedlacek I this we need to be more careful as the API we are using isn't in our control and it might go down if some random users repeatedly did pull to refresh!

Also, I don't think that features will get updated frequently (in minutes/seconds let's say) since it's not user related content for example.

2023-02-21 21:02 UTC, JamesSedlacek commented
Agreed. My thought process is that we need a way for the user to load the data if it fails. Maybe a better option would be a screen that says "Something went wrong" with a "Try Again" button ?

2023-02-21 21:17 UTC, cs4alhaider commented
Yes, that’s a good idea!

2023-02-21 22:12 UTC, jordibruin commented
@cs4alhaider I've talked to the creator of countapi a while ago and they're getting millions of requests each day so a little pull to refresh shouldn't hurt anyone! Reopening this so we can discuss it more openly.

2023-02-22 10:53 UTC, AvdLee requested changes

2023-02-22 10:53 UTC, AvdLee commented on Sources/Roadmap/RoadmapViewModel.swift
> +        loadFeatures(roadmapJSONURL: configuration.roadmapJSONURL)
If we can ensure to 
- only refresh once every 5 minutes (to prevent lots of unneeded refreshes)
- refresh if not already refreshing

I think it would be a valuable addition. However, like you mentioned, you can question how much need there is from a user perspective to refresh a list of features. The use case is likely small, but being able to refresh in case of failure would be super valuable.

Therefore, I think we can implement both a limited pull to refresh as described above and a failure screen with a refresh button.

I realise we're asking a bit more here now, but I'm happy to provide you feedback so you can learn from the contribution along the way!

2023-02-22 12:34 UTC, cs4alhaider commented
@jordibruin my point war for the features API (cms), regarding the count api to be honest I didn't think about it.

@AvdLee your points is good, having a timer to limit the hits will defiantly help!

2023-07-28 16:54 UTC, AvdLee commented
Closing this PR for inactivity, let me know if you want to continue it.

2023-07-28 16:54 UTC, closed without merging