Add FeatureVoter Abstraction
AvdLee/Roadmap pull request #38
Opened 2023-02-23 12:04 UTC by Sherlouk

Relates to #33 but doesn't necessarily close it. This PR separates "FeatureVoter" (an abstraction) from "FeatureVoterCountAPI" (the default concrete implementation).

This is not a breaking change, and will continue to default to using the CountAPI solution but does now give clients the ability to implement their own solution (such as their own persistence API).

2023-02-23 17:53 UTC, AvdLee requested changes
Yesss, I love this! Let's actually make this usable by adjusting the initializer and we're good to merge. Thanks as well for writing the test!

2023-02-23 17:53 UTC, AvdLee commented on Sources/Roadmap/RoadmapConfiguration.swift
> +        self.voter = FeatureVoterCountAPI(namespace: namespace)
Let's add a property `voter` to the initializer with this as the default fallback:

```swift
    public init(roadmapJSONURL: URL, namespace: String? = nil, style: RoadmapStyle = RoadmapTemplate.standard.style, shuffledOrder: Bool = false, voter🙂FeatureVoter? = nil) {
    // ...
    self.voter = voter ?? FeatureVoterCountAPI(namespace: namespace)
```

2023-02-23 17:55 UTC, Sherlouk commented on Sources/Roadmap/RoadmapConfiguration.swift
> +        self.voter = FeatureVoterCountAPI(namespace: namespace)
Is this needed? The namespace parameter is used only by CountAPI and so the expectation is if you're using the default initialiser (or explicitly providing the namespace) then that is your intent.

A separate initialiser had all the same parameters, except replacing the optional namespace with a required voter parameter.

Both options are present!

2023-02-24 07:43 UTC, AvdLee commented on Sources/Roadmap/RoadmapConfiguration.swift
> +        self.voter = FeatureVoterCountAPI(namespace: namespace)
Ah, I completely missed the initializer underneath this comment, all good in that case! 

Last point: would you mind writing a little instruction in the readme to finish this feature? That way, others can find the option more easily!

2023-02-24 09:44 UTC, Sherlouk commented on Sources/Roadmap/RoadmapConfiguration.swift
> +        self.voter = FeatureVoterCountAPI(namespace: namespace)
Absolutely, I'll update the README.

2023-02-24 10:22 UTC, Sherlouk commented
README updated: I've removed the FAQ as it is now encapsulated in the paragraph above and so felt unnecessary to duplicate information.

2023-02-24 14:41 UTC, jordibruin commented
This is so nice @Sherlouk !!

2023-02-24 19:10 UTC, shaps80 commented
Yep I agree. Very nice. Solve the dep injection of a custom voting backend.

I actually also made some great progress with my suggestions. I'll make a Pr over the weekend. It's almost done.

It'd work well alongside this change as well.

2023-02-26 14:54 UTC, AvdLee approved these changes
Love the quality of this contribution, thanks a lot for helping us out here!

2023-02-26 14:54 UTC, AvdLee commented
@Sherlouk once the merge conflict is solved, we can merge it in!

2023-02-26 15:26 UTC, Sherlouk commented
@AvdLee - done 🎉

2023-03-05 09:51 UTC, merged

2023-03-05 09:51 UTC, AvdLee commented
@Sherlouk merged, thanks a lot!!