Added Progress View While Loading Content
AvdLee/Roadmap pull request #44
Opened 2023-02-25 19:33 UTC by cs4alhaider

Added support to show a progress view while loading..

2023-02-26 15:01 UTC, AvdLee requested changes
Thanks a lot for your contribution! The start is great, but there's something we need to change to be better prepared for the future & performance impact

2023-03-09 08:49 UTC, AvdLee requested changes

2023-03-10 08:44 UTC, cs4alhaider commented on Sources/Roadmap/Extensions/ViewExtensions.swift
> +            self
Yes correct this will remove `self`, I don't think this is an issue since it's very cheap and fast.

2023-03-10 13:22 UTC, AvdLee commented on Sources/Roadmap/Extensions/ViewExtensions.swift
> +            self
It is an issue since we will reload all votes for the Features, since we will redraw those

2023-03-14 05:24 UTC, noppefoxwolf commented on Sources/Roadmap/Extensions/ViewExtensions.swift
> +                ProgressView()
it's prefer to use `redacted ` than `ProgressView`.

https://developer.apple.com/documentation/swiftui/menu/redacted(reason:)

What do you think about it? @AvdLee

2023-07-28 16:57 UTC, AvdLee commented
Closing this PR due to inactivity. Feel free to reopen if you're ready to pick up the feedback and updating with `main`!

2023-07-28 16:57 UTC, closed without merging