🔓 Enable optional advanced requests for the roadmap endpoint
AvdLee/Roadmap pull request #50
Opened 2023-02-28 22:00 UTC by codebeauty

🧐 **Problem**
As a developer I want to be able to point to a roadmap endpoint which is protected. Currently I can only provide a simple URL. This is nice, but we need one more step.

💡 **Solution:**
In many cases the protection works by a bearer token inside the request header. A way to handover a Request instead of only the URL helps to set a header for the authentication against the backend like...

```
var request = URLRequest(url: URL(string: "https://my-protected-endpoint-url-to-the-roadmap-features"))
request.setValue("application/json", forHTTPHeaderField: "Content-Type")
request.setValue("Bearer 1234567890", forHTTPHeaderField: "Authorization")

configuration = RoadmapConfiguration(
        roadmapRequest: request,
        ...
```

✍️ **Changes:**

- updated configuration for an optional URLRequest instead of a URL for an advanced way to fetch the roadmap
- updated previews for both simple or advanced requests

Keep up the good work. 👏

2023-03-01 12:29 UTC, jordibruin commented
Awesome! Could this be something we can combine with https://github.com/AvdLee/Roadmap/pull/38

2023-03-05 09:56 UTC, AvdLee requested changes
Great job! I totally believe this is a valuable addition. I've provided some feedback

2023-03-05 09:56 UTC, AvdLee commented on Sources/Roadmap/RoadmapFeatureView.swift
> +
Correct me if I'm wrong, but the UI doesn't change when using a request over a URL. Therefore, it's better to not add a specific preview for it since it would make other developers think it does change the UI.

```suggestion
```

2023-03-05 09:56 UTC, AvdLee commented on Sources/Roadmap/RoadmapView.swift
> +                .previewDisplayName("Roadmap via Request")
Same as previous comment

```suggestion
```

2023-03-05 09:56 UTC, AvdLee commented on Sources/Roadmap/RoadmapViewModel.swift
> +        }
We can simplify this code by transforming the input URL to a request as well, and make all logic work with `URLRequest` instead. If you like, I'm happy to review such change as well! 

It reduces duplicated code, reduces if statements, and we can reuse initialisers. Let me know your thoughts!

2023-03-05 12:32 UTC, jordibruin commented
Can we determine what we need to change to merge this PR?

2023-03-05 21:07 UTC, closed without merging

2023-03-05 21:21 UTC, codebeauty commented on Sources/Roadmap/RoadmapFeatureView.swift
> +
Good Point, the idea was just to use it as a example check for the different use cases, but a test for that would be clearer.

2023-03-05 21:22 UTC, codebeauty commented on Sources/Roadmap/RoadmapViewModel.swift
> +        }
Yes, that is really more clean. I will make a proposal.

2023-03-05 21:22 UTC, codebeauty commented
Will come back later this week. 🫠