[WIP] Issues 7 and 8
AvdLee/Roadmap pull request #59
Opened 2023-03-12 22:26 UTC by iOSjess

Resolve #7, resolve #8  

I chose a menu-style picker for space optimization as I considered adding the sorting option (also a menu-style picker) to the top right of the screen. I considered using an icon instead of the "Filter" label but wanted your input.

2023-03-20 09:16 UTC, jordibruin commented
Wow! thanks for this ! @hiddevdploeg @AvdLee

2023-03-20 09:19 UTC, AvdLee approved these changes
Nice, smart way of solving support for 'any' statuses by just reading them from the JSON!

2023-03-20 09:19 UTC, AvdLee commented
@iOSjess to be sure, have you tested this on the Mac as well?

2023-03-25 18:18 UTC, iOSjess commented
> @iOSjess to be sure, have you tested this on the Mac as well?

I haven't. I can test that this weekend. I was also wondering, should this be a choice for the developer to turn on like @jordibruin did with the search bar?

2023-04-04 22:57 UTC, iOSjess commented
@AvdLee I did some testing on the Mac version as well and made some UI adjustments. I'm also adding a sort button for sorting by number of votes.

2023-04-06 21:17 UTC, jordibruin commented
I haven't looked through the changes yet, but how are you sorting by votes since the votes get retrieved once the item is in view? Very interesting! (I should just look through the code sorry for my laziness)

2023-04-09 19:06 UTC, iOSjess commented
> I haven't looked through the changes yet, but how are you sorting by votes since the votes get retrieved once the item is in view? Very interesting! (I should just look through the code sorry for my laziness)

I've actually been struggling to make the solution for that very thing. There will likely be an overhaul involved to do the sorting by votes. I'm going to finalize this PR for just the filtering by status.

2023-05-28 22:35 UTC, iOSjess commented
> @iOSjess is this ready for review?

Yes.

2023-07-05 12:36 UTC, AvdLee requested changes
Looks good overall, I just have a few improvements we can make

2023-07-05 12:36 UTC, AvdLee commented on Sources/Roadmap/RoadmapViewModel.swift
> +    @Published var statusToFilter = "all"
Could we use an enum for this for type safety?

2023-07-28 16:59 UTC, AvdLee commented
@iOSjess would you like to continue this PR? Would be a nice addition!

2024-01-15 17:27 UTC, iOSjess commented on Sources/Roadmap/RoadmapViewModel.swift
> +    @Published var statusToFilter = "all"
@AvdLee Sorry I disappeared for a while there. Life got in the way. I'm not sure how we could make this an Enum since all other "Status" values are being pulled in from the JSON

2024-01-15 17:29 UTC, iOSjess commented on Sources/Roadmap/RoadmapView.swift
> +                    .tint(.black)
Fixed

2024-02-21 14:06 UTC, AvdLee approved these changes
Thanks a lot for your contribution!

2024-02-21 14:06 UTC, merged